login:
    path:     /login
    defaults: { _controller: MakeupBundle:User:login }
    
login_check:
    path:     /login_check
    
logout:
    path:     /logout
    
makeup_lang:
    path: /lang/{_locale}
    defaults: { _controller: MakeupBundle:Default:lang }

makeup_homepage:
    path:     /
    defaults: { _controller: MakeupBundle:Default:index }

makeup_comments:
    path:     /comments
    defaults: { _controller: MakeupBundle:Default:comments}

makeup_treatments:
    path:     /treatments
    defaults: { _controller: MakeupBundle:Default:treatments }
